functional:
  - Искать товары по ключевому слову или категории
  - Фильтр по всем товарам
  - Просматривать товары и просматривать подробную|
    информацию такую как рейтинг, скидка, описание. 
  - Добавлять товары в корзину и просматривать содержимое корзины
  - Переключать язык интерфейса
  - Возможность продолжить покупки после оформления заказа
  - Оформление заказа с переходом на страницу оплаты
non-functional:
  - Разработка с учетом удобства использования и оптимизировать для скорости работы
  - Безопасным и защищать данные пользователя
  - Иметь мобильную версию
  - Протестировать на совместимость с последними версиями браузеров
  - Должен быть доступен на различных устройствах
  - Иметь локализацию (перевод) на русский и английский языки
  - Важно,  обрабатывать большое количество трафика
  - Хранине данных корзины в ссесии блаузера
implicit:
  - Простота использования
  - Информация на сайте должна быть "легкой"
  - Поиск  по сайту мультиязычный
  - Шифрование данных
  - Разработка моб. версии
  - Корректная работа сайта во всех блаузерах и устройствах
  - Мультиязычный сайт
  
  
