functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Cайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Простота использования
  - Информация на сайте должна быть "легкой"
  - Ввод пароля со спец символами и разным регистром
  - Двойное шифрование данных
  - Разработка моб. версии
  - Корректная работа сайта во всех блаузерах и устройствах
  - Для разнонациональной  аудитории
  
