functional:
  - Искать товары по ключевому слову или категории
  - Фильтр по всем товарам
  - просматривать товары и просматривать подробную информацию о товаре
  - добавлять товары в корзину и просматривать содержимое корзины
  - переключать язык интерфейса
non-functional:
  - разработка с учетом удобства использования и оптимизировать для скорости работы
  - безопасным и защищать данные пользователя
  - иметь мобильную версию
  -  протестировать на совместимость с последними версиями браузеров
  -  должен быть доступен на различных устройствах
  -  иметь локализацию (перевод) на русский и английский языки
  - Важно,  обрабатывать большое количество трафика
implicit:
  - Простота использования
  - Информация на сайте должна быть "легкой"
  - Поиск  по сайту мультиязычный
  - Шифрование данных
  - Разработка моб. версии
  - Корректная работа сайта во всех блаузерах и устройствах
  - Мультиязычный сайт
  
